import 'package:flutter/material.dart';
import 'package:shop_app/models/page_view_model.dart';
import 'package:shop_app/models/product.dart';

class MyProvider extends ChangeNotifier {
  int currentIndex = 0; // this in image slider
  bool colorState = true; // this in product details screen for favorite icon
  Color color= null;     // this in product details screen for favorite icon color
  IconData icon = Icons.favorite_border; // this in product details screen for icon
  Color backColor = Colors.white;      //used in background of theme mode of all app

  void changeColor(){
    backColor = backColor == Colors.white ? Colors.black:Colors.white;
    notifyListeners();
  }

  List<PageData> pageList = [  //this used in pageView
    PageData(
      title: "Fruits 1",
      description: "You can puy a collection of fruits \n by cards",
      imageUrl: 'assets/images/1.jpg',
    ),
    PageData(
      title: "Fruits 2",
      description: "You can puy a collection of fruits \n by cards",
      imageUrl: 'assets/images/2.jpg',
    ),
    PageData(
      title: "Clothes 1",
      description: "You can puy a collection of clothes \n by cards",
      imageUrl: 'assets/images/3.jpg',
    ),
    PageData(
      title: "Clothes 2",
      description: "You can puy a collection of clothes \n by cards",
      imageUrl: 'assets/images/4.jpg',
    )
  ];

  List<String> imgList = [
    'assets/images/f1.jpg',
    'assets/images/c1.jpg',
    'assets/images/f2.jpg',
    'assets/images/c2.jpg',
    'assets/images/f3.jpg',
    'assets/images/c3.jpg',
  ];

  List<Productt> productList = [
    Productt(
      id: '1',
      name: 'Camera xd',
      imageUrl: 'assets/images/p1.jpg',
      price: 250.0,
      description: ['A product description to potential customers ',
                   'is usually complete, informative and concise.',
                    'A product description to potential customers ',
                    'is usually complete, informative and concise.',
                    'A product description to potential customers ',
                    'is usually complete, informative and concise.',
                    'A product description to potential customers ',
                    'is usually complete, informative and concise.',
                    'A product description to potential customers ',
                    'is usually complete, informative and concise.',
                    'A product description to potential customers ',
                    'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '2',
      name: 'Stars',
      imageUrl: 'assets/images/p2.jpg',
      price: 180.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '3',
      name: 'Short hd',
      imageUrl: 'assets/images/p3.jpg',
      price: 150.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '4',
      name: 'Cream floda',
      imageUrl: 'assets/images/p4.jpg',
      price: 50.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '5',
      name: 'Whey proten',
      imageUrl: 'assets/images/p5.jpg',
      price: 1000.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '6',
      name: 'Iphone 13',
      imageUrl: 'assets/images/p6.jpg',
      price: 1700.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '7',
      name: 'Camera kkl',
      imageUrl: 'assets/images/p7.jpg',
      price: 700.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '8',
      name: 'Recharger',
      imageUrl: 'assets/images/p8.jpg',
      price: 100.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '1',
      name: 'Camera xd',
      imageUrl: 'assets/images/p1.jpg',
      price: 250.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '2',
      name: 'Stars',
      imageUrl: 'assets/images/p2.jpg',
      price: 180.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '3',
      name: 'Short hd',
      imageUrl: 'assets/images/p3.jpg',
      price: 150.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '4',
      name: 'Cream floda',
      imageUrl: 'assets/images/p4.jpg',
      price: 50.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '5',
      name: 'Whey proten',
      imageUrl: 'assets/images/p5.jpg',
      price: 1000.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '6',
      name: 'Iphone 13',
      imageUrl: 'assets/images/p6.jpg',
      price: 1700.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '7',
      name: 'Camera kkl',
      imageUrl: 'assets/images/p7.jpg',
      price: 700.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
    Productt(
      id: '8',
      name: 'Recharger',
      imageUrl: 'assets/images/p8.jpg',
      price: 100.0,
      description: ['A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
        'A product description to potential customers ',
        'is usually complete, informative and concise.',
      ],
    ),
  ];

List<Productt> favoritesList = [];


bool isFavorite(String idd){
  return favoritesList.any((product) => product.id == idd );
}



void add_Or_remove_FavoriteProduct(idd){
  if(!isFavorite(idd)){
    favoritesList.add(productList.firstWhere((product) => product.id == idd));
  }else{
    final existingIndex = favoritesList.indexWhere((product) => product.id == idd );
    favoritesList.removeAt(existingIndex);
  }
  notifyListeners();
}



}
